name: Build,Push and Deploy to GKE
on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  IMAGE_NAME: hello-ms
  GKE_CLUSTER: autopilot-cluster-1
  REGION: europe-west1
  DEPLOYMENT_NAME: hello-ms

jobs:
  build-push-gcr:
    name: Build and Push to GCPBuild and Push to GCP
    runs-on: ubuntu-latest

    permissions:
      id-token: write 
      contents: read  

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Authenticate to WIF
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/507085571061/locations/global/workloadIdentityPools/gke-pool-tung/providers/gke-playground-provider
          service_account: github-actions@cst-pbag-aiml-test.iam.gserviceaccount.com
          token_format: access_token
          export_environment_variables: true
    
      - name: Automatic Tagging of Releases
        id: increment-git-tag
        run: |
          bash ./scripts/git_update_tag.sh -v patch

      - name: Build and push Docker image
        env:
          GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
          CONTAINER_REGISTRY: europe-west1-docker.pkg.dev
        run: |-
          docker pull $CONTAINER_REGISTRY/$PROJECT_ID/gke-playground/$IMAGE_NAME:latest
          DOCKER_IMAGE_VERSION=$(docker inspect --format '{{ index .Config.Labels "version" }}' $CONTAINER_REGISTRY/$PROJECT_ID/gke-playground/$IMAGE_NAME:latest)
          echo "Latest Docker image version: $DOCKER_IMAGE_VERSION"
