name: Build and Push Docker Image to GCP
on:
  push:
    branches: [main]

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  IMAGE_NAME: hello-ms
  GKE_CLUSTER: autopilot-cluster-1
  REGION: europe-west1
  DEPLOYMENT_NAME: hello-ms

jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install gcloud cli
        uses: google-github-actions/setup-gcloud@main
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}
          export_default_credentials: true

      - name: Authenticate with gcloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}

      - name: Automatic Tagging of Releases
        id: increment-git-tag
        run: |
          bash ./scripts/git_update.sh -v major

      - name: Build and push Docker image
        env:
          GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
        run: |-
          gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet
          docker build -t europe-west1-docker.pkg.dev/$PROJECT_ID/gke-playground/$IMAGE_NAME:latest .
          docker build -t europe-west1-docker.pkg.dev/$PROJECT_ID/gke-playground/$IMAGE_NAME:$GIT_TAG .
          docker push europe-west1-docker.pkg.dev/$PROJECT_ID/gke-playground/$IMAGE_NAME:latest
          docker push europe-west1-docker.pkg.dev/$PROJECT_ID/gke-playground/$IMAGE_NAME:$GIT_TAG

      - name: Get GKE credentials
        uses: 'google-github-actions/get-gke-credentials@v1'
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.REGION }}

      - name: Deploy to GKE
        run: |-
          sed -i "s/PROJECT_ID/$PROJECT_ID/g" gke-deployment.yml
          sed -i "s/IMAGE_NAME/$IMAGE_NAME/g" gke-deployment.yml
          sed -i "s/MY_LABEL/$MY_LABEL/g" gke-deployment.yml
          kubectl apply -f gke-deployment.yml